#INCLUDE "P16F877A.INC"
	

LCD_DATA        EQU	PORTB          
LCD_DATA_TRIS   EQU	TRISB
LCD_CTRL        EQU	PORTB         
LCD_E           EQU	6                         
LCD_RS          EQU	7  

#DEFINE BUZZER PORTC, 0

CBLOCK 0X20
A1, A2, A3, TEMPERATURE, RETURNED_VALUE
LCD_TEMP, LCD_TEMP1, LCD_DATA_TEMP

ENDC

	ORG		0X000
	GOTO	MAIN
	ORG		0X04
	BCF		INTCON, INTF
	BCF		BUZZER
	RETFIE


MAIN
	CALL	SETUP		
	CALL	LCDINIT			
	CALL	LCDCLEAR		

LOOP
	CALL	LCDLIN1
	CALL	M1

	CALL	LCDLIN2
	CLRF	PORTD
REP
	CALL	CHECK
	MOVWF	RETURNED_VALUE

	CALL    LCDPUTCHAR
	MOVF	RETURNED_VALUE, W
	XORLW	'H'
	BTFSC	STATUS, Z
	BSF		BUZZER

	MOVF	RETURNED_VALUE, W
	XORLW	'T'
	BTFSC	STATUS, Z
	BSF		BUZZER

	MOVF	RETURNED_VALUE, W
	XORLW	'B'
	BTFSC	STATUS, Z
	BSF		BUZZER
	
	CALL	DELAY_1S
	INCF	PORTD, F
	BTFSS	PORTD, 4
	GOTO	REP
	CLRF	PORTD
	GOTO	LOOP

CHECK
	CALL	A2D_CHANEL_0
	MOVWF	TEMPERATURE

	MOVLW	D'36'
	SUBWF	TEMPERATURE, W
	BTFSS	STATUS, C
	RETLW	'L'
	MOVF	TEMPERATURE, W
	SUBLW	D'38'
	BTFSS	STATUS, C
	RETLW	'H'

	BTFSC	PORTE, 0
	RETLW	'B'
	RETLW	'.'


M1
    MOVLW    '0'
    CALL    LCDPUTCHAR
    MOVLW    '1'
    CALL    LCDPUTCHAR
    MOVLW    '2'
    CALL    LCDPUTCHAR
    MOVLW    '3'
    CALL    LCDPUTCHAR
    MOVLW    '4'
    CALL    LCDPUTCHAR
    MOVLW    '5'
    CALL    LCDPUTCHAR
    MOVLW    '6'
    CALL    LCDPUTCHAR
    MOVLW    '7'
    CALL    LCDPUTCHAR
    MOVLW    '8'
    CALL    LCDPUTCHAR
    MOVLW    '9'
    CALL    LCDPUTCHAR
    MOVLW    'A'
    CALL    LCDPUTCHAR
    MOVLW    'B'
    CALL    LCDPUTCHAR
    MOVLW    'C'
    CALL    LCDPUTCHAR
    MOVLW    'D'
    CALL    LCDPUTCHAR
    MOVLW    'E'
    CALL    LCDPUTCHAR
    MOVLW    'F'
    CALL    LCDPUTCHAR
    RETURN


SETUP
	CLRF	PORTA
	CLRF	PORTB
	CLRF	PORTC
	CLRF	PORTD
	CLRF	PORTE
	BSF 	STATUS, RP0
	MOVLW	B'00000101'
	MOVWF	ADCON1
	MOVLW	B'00000111'
	MOVWF	CMCON
	MOVLW	B'00111111'
	MOVWF	TRISA
	MOVLW	B'00000001'
	MOVWF	TRISB
	MOVLW	B'00000000'
	MOVWF	TRISC
	MOVLW	B'00000000'
	MOVWF	TRISD
	MOVLW	B'00000111'
	MOVWF	TRISE
	BCF 	STATUS, RP0
	BSF		INTCON, GIE
	BSF		INTCON, INTE
	RETURN

A2D_CHANEL_0
	MOVLW	B'01000001'		; Fosc/8, and select CHANNEL 0
	MOVWF	ADCON0	
	CALL	A2D_DELAY
	BSF     ADCON0,GO       ;Start A/D conversion
	BTFSC   ADCON0,GO       ;Wait for conversion to complete
    GOTO    $-1
	MOVF    ADRESH,W		; PUT ADRESH IN W
    RETURN

A2D_DELAY					; AQUISITION TIME	~20US
	MOVLW	D'5'
	MOVWF	A1
	DECFSZ	A1, F
	GOTO	$-1
	RETURN


LCDINIT
    CLRF 	LCD_CTRL                                    
  	CALL	DELAY_20MS 	
                                      
    MOVLW  	B'00110000'            
    CALL    LCDPUTNIBBLE		
    CALL	DELAY_20MS

    MOVLW  	B'00110000'             
    CALL    LCDPUTNIBBLE
    CALL	DELAY_1MS

    MOVLW  	B'00110000'           
    CALL    LCDPUTNIBBLE 
	CALL	DELAY_1MS

	MOVLW  	B'00100000'             
    CALL    LCDPUTNIBBLE 
	CALL	DELAY_1MS
	MOVLW  	B'00101000'            
    CALL    LCDPUTCMD 
    MOVLW 	B'00001000'
	CALL	LCDPUTCMD
    CALL	LCDCLEAR
    MOVLW	B'00001100'               
    CALL	LCDPUTCMD
    MOVLW	B'00000110'              
    CALL	LCDPUTCMD
    RETURN

;--------------------------------------------------------------------------------
LCDPUTCHAR
	MOVWF	LCD_TEMP            
   	CALL	DELAY_1MS             
    CALL	DELAY_1MS     	    
	MOVF	LCD_TEMP, W
 	ANDLW	B'11110000'
  CALL	LCD_DATA_PLACE 
 
	BSF		LCD_CTRL, LCD_RS	; write data on lcd and not a command
	BSF     LCD_CTRL, LCD_E		; falling edge on E line
	NOP
	NOP       
	BCF     LCD_CTRL, LCD_E
	SWAPF	LCD_TEMP, W
	ANDLW	B'11110000'
  	CALL	LCD_DATA_PLACE 

	BSF		LCD_CTRL, LCD_RS
	BSF		LCD_CTRL, LCD_E
	NOP
	NOP 
	BCF		LCD_CTRL, LCD_E  
	RETURN

;--------------------------------------------------------------------------------
LCDPUTCMD
   	MOVWF	LCD_TEMP            
   	CALL	DELAY_1MS  
   	CALL	DELAY_1MS            
   	MOVF	LCD_TEMP, W
   	ANDLW	B'11110000'
  	CALL	LCD_DATA_PLACE 

   	BCF		LCD_CTRL, LCD_RS 	
	BSF		LCD_CTRL, LCD_E
	NOP
	NOP       
   	BCF		LCD_CTRL, LCD_E	
   	SWAPF	LCD_TEMP, W
   	ANDLW	B'11110000'
    CALL	LCD_DATA_PLACE 
  
   	BCF		LCD_CTRL, LCD_RS 
	BSF		LCD_CTRL, LCD_E
	NOP
	NOP       
   	BCF		LCD_CTRL, LCD_E
   	RETURN

LCDPUTNIBBLE
	MOVWF	LCD_TEMP            
    MOVF	LCD_TEMP, W
    ANDLW	B'11110000'
    CALL	LCD_DATA_PLACE 

    BCF		LCD_CTRL, LCD_RS    
    BSF		LCD_CTRL, LCD_E 
	NOP
	NOP
	BCF		LCD_CTRL, LCD_E
	RETURN


LCD_DATA_PLACE
	CLRF	LCD_DATA
	BSF		PORTB, 1
	MOVWF	LCD_DATA_TEMP
	BTFSC	LCD_DATA_TEMP, 7
	BSF		LCD_DATA, 2
	BTFSC	LCD_DATA_TEMP, 6
	BSF		LCD_DATA, 3
	BTFSC	LCD_DATA_TEMP, 5
	BSF		LCD_DATA, 4
	BTFSC	LCD_DATA_TEMP, 4
	BSF		LCD_DATA, 5
	RETURN


;--------------------------------------------------------------------------------
LCDCLEAR
    	MOVLW       0x01
    	CALL        LCDPUTCMD
    	RETURN

LCDLIN1		
	MOVLW	B'10000000'         
    CALL	LCDPUTCMD
	RETURN

LCDLIN2			
	MOVLW	B'11000000'         
    CALL	LCDPUTCMD
	RETURN


DELAY_1S 
	NOP
	MOVLW	D'46'
	MOVWF	A3
	MOVLW	D'189'
	MOVWF	A2
	MOVLW	D'37'
	MOVWF	A1
	CLRWDT
	DECFSZ 	A1,F
	GOTO	$-2	
	DECFSZ	A2,F
	GOTO	$-6
	DECFSZ	A3, F
	GOTO	$-D'10'
	RETURN


DELAY_20MS
    MOVLW    D'5'
    MOVWF    A3
    MOVLW    D'17'
    MOVWF    A2
    MOVLW    D'77'
    MOVWF    A1
    DECFSZ   A1, F
    GOTO     $-1
    DECFSZ   A2, F
    GOTO     $-5
    DECFSZ   A3, F
    GOTO     $-9
    RETURN

DELAY_1MS 
	MOVLW	D'5'
	MOVWF	A3
	MOVLW	D'15'
	MOVWF	A2
	MOVLW	D'5'
	MOVWF	A1
	DECFSZ 	A1,F
	GOTO	$-1	
	DECFSZ	A2,F
	GOTO	$-5
	DECFSZ	A3, F
	GOTO	$-9
	RETURN


END